services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mindalpha-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mindalpha-frontend
    ports:
      - "5500:80"
    depends_on:
      - backend
